# Generated by Django 5.2 on 2025-06-10 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZYLO_SELLER', '0002_category_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the product.', max_length=255)),
                ('price', models.DecimalField(decimal_places=2, help_text='The price of the product.', max_digits=10)),
                ('image', models.ImageField(blank=True, help_text='Main image for the product.', null=True, upload_to='products/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='The main category for this product.', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='ZYLO_SELLER.category')),
                ('seller', models.ForeignKey(help_text='The seller offering this product.', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='ZYLO_SELLER.sellerprofile')),
                ('subcategory', models.ForeignKey(blank=True, help_text='Optional subcategory for this product.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='ZYLO_SELLER.subcategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
