# Generated by Django 5.2 on 2025-06-10 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZYLO_SELLER', '0003_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='on_sale',
            field=models.BooleanField(default=False, help_text='Indicates if the product is currently on sale.'),
        ),
    ]
