# Generated by Django 5.2 on 2025-06-10 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZYLO_SELLER', '0006_product_brand_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='on_sale',
            field=models.BooleanField(default=True, help_text='Indicates if the product is currently on sale.'),
        ),
    ]
