# Generated by Django 5.2 on 2025-06-12 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ZYLO_SELLER', '0007_alter_product_on_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
