# Generated by Django 5.2 on 2025-06-12 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZYLO_SELLER', '0008_remove_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='model_name',
            field=models.CharField(blank=True, help_text="The model name of the product variant (e.g., 'Nike Air Max').", max_length=100, null=True),
        ),
    ]
