# Generated by Django 5.2 on 2025-06-16 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZYLO_SELLER', '0009_productvariant_model_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='color_hex',
            field=models.CharField(blank=True, help_text="The hexadecimal color code for this variant (e.g., '#FF5733').", max_length=7, null=True),
        ),
    ]
