# Generated by Django 5.2 on 2025-06-18 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZYLO_SELLER', '0010_productvariant_color_hex'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image for the category.', null=True, upload_to='category_images/'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image for the subcategory.', null=True, upload_to='subcategory_images/'),
        ),
    ]
