# Generated by Django 5.2 on 2025-06-30 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZYLO_SELLER', '0011_category_image_subcategory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='variant_name',
            field=models.CharField(blank=True, help_text="The display name of this variant (e.g., 'Productname(product name) or series name + color and size (Black 256GB)').", max_length=100, null=True),
        ),
    ]
