# Generated by Django 5.2 on 2025-06-25 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZYLO_WEB', '0003_cart_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_wishlist',
            name='cart',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='cart_wishlist',
            name='wishlist',
            field=models.TextField(default='[]'),
        ),
    ]
